version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  meetapp:
    container_name: meetapp
    build: .
    restart: always
    env_file: 
      - ./config/config.env
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: