-
  name: Install and Configure Java, Docker, gcloud CLI, and Trivy on GCP worker instances
  hosts: gcp_worker
  become: yes
  tasks: 
    - name: Update Apt Cache
      apt:
        update_cache: yes
    
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk-headless
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Ensure Docker socket is accessible
      file:
        path: /var/run/docker.sock
        mode: '0777'
        state: touch

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Install Dependencies for Gcloud CLI
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
        state: present

    - name: Add Gcloud Repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk.list
        state: present

    - name: Install Gcloud CLI
      apt:
        name: google-cloud-cli
        state: present
        update_cache: yes

    - name: Configure gcloud CLI (Manual Step)
      debug:
        msg: "Run 'gcloud auth login' manually to set up GCP credentials."

    - name: Install Dependencies for Trivy
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present

    - name: Add Trivy GPG
      shell: | 
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -

    - name: Add Trivy Repository
      shell: |
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list

    - name: Install Trivy
      apt:
        name: trivy
        state: present
        update_cache: yes

    - name: Print Completed Message
      debug:
        msg: "Java, Docker, gcloud CLI, and Trivy have been installed and configured on the worker instance."