kind: Deployment
apiVersion: apps/v1
metadata:
  name: ourmeet
  namespace: meetapp
  labels:
    app: meet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meet
  template:
    metadata:
      labels:
        app: meet
    spec:
      containers:
        - name: meetapp
          image: guravarchies/meet-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: LIVE_DB
              valueFrom:
                configMapKeyRef:
                  name: meetapp-config
                  key: LIVE_DB

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: meetapp
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc