kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  namespace: meetapp
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"